name: lexer
author: Conrad Kleinespel <conradk@conradk.com>
description: Lexing tools for Dart - under development
homepage: https://github.com/conradkleinespel/lexer-dart
dependencies:
  unittest: "0.10.0"
