name: lexer
version: 0.0.0
author: Conrad Kleinespel <conradk@conradk.com>
description: Lexing tools for Dart - under development
homepage: https://github.com/conradkleinespel/lexer-dart
dev_dependencies:
  unittest: "0.10.0"
